author: xinyi
height: 1544
width: 2064
obj_height: 14
table_distance: 1195
calibmat_path: /home/hlab/bpbot/data/calibration/calibmat.txt
real2pixel: 1.953020134228188
force_sensor:
  sensitivity: [32.800,32.815,32.835,1653.801,1634.816,1636.136]
exp:
  lr_arm: left
  mode: fge
  camera_mode: true
  log_mode: false
  motionfile_mode: true
  rigid_mode: true
main:
  height:
    max: 0.03089223851703827
    min: -0.03423492190242783
  area:
    left: 890
    top: 524
    right: 1357
    bottom: 985
position:
  hot_water: [0.500, 0.200]
  cold_water: [0.450, 0.200]
  place: [0.505, -0.300]
graspability:
  rotation_step: 45
  depth_step: 10
  hand_depth: 20
hand:
  left:
    type: thk_soft
  right:
    type: smc_ft
