author: xinyi
height: 1544
width: 2064
obj_height: 15
calibmat_path: /home/hlab/bpbot/data/calibration/calibmat.txt
real2pixel: 1.8964690210979784
exp:
  play_mode: 1
  grasp_mode: fge
  iteration: 1
  k_stop: 2.5
  k_fail: 0.7
  lr_arm: right
  log_mode: 1
force_sensor:
  sensitivity:
  - 32.8
  - 32.815
  - 32.835
  - 1653.801
  - 1634.816
  - 1636.136
main:
  height:
    max: 0.0807229218388672
    min: -0.0518527307068577
  area:
    left: 698
    top: 337
    right: 1768
    bottom: 1226
buffer:
  height:
    max: 0.05033891982656879
    min: 0.010372077580194539
  area:
    left: 565
    top: 499
    right: 1056
    bottom: 1045
graspability:
  rotation_step: 22.5
  depth_step: 10
  hand_depth: 20
hand:
  left:
    type: smc_rcc
  right:
    type: smc_ft
