author: xinyi
height: 1544
width: 2064
obj_height: 14
table_distance: 1195
calibmat_path: /home/hlab/bpbot/data/calibration/calibmat.txt
real2pixel: 2.0344539187762356
exp:
  lr_arm: left
  mode: fge
  camera_mode: True
  log_mode: False
  motionfile_mode: False
  destination: side
main:
  height:
    max: 0.0807229218388672
    min: -0.0518527307068577
  area:
    left: 698
    top: 337
    right: 1768
    bottom: 1226
graspability:
  rotation_step: 22.5
  depth_step: 10
  hand_depth: 20
hand:
  left:
    type: smc_rcc
  right:
    type: smc_ft
tangle:
  compressed_size: 250
  len_thld: 15
  dist_thld: 3
  sliding_size: 225
  sliding_stride: 10
