schunk:
  finger_length: 12
  finger_width: 5
  open_width: 25
  tool_changer_height: 31
  flange_height: 6
  finger_height: 80
  gripper_height: 48
smc:
  finger_length: 8
  finger_width: 4
  open_width: 46
  tool_changer_height: 31
  flange_height: 3
  gripper_height: 25
  finger_height: 80
smc_ft:
  finger_length: 25
  finger_width: 8
  open_width: 48
  tool_changer_height: 31
  flange1_height: 6
  force_sensor_height: 32
  flange2_height: 11
  gripper_height: 25
  finger_height: 86
smc_rcc:
  finger_length: 25
  finger_width: 8
  open_width: 48
  tool_changer_height: 31
  flange1_height: 6
  rrc_height: 25
  flange2_height: 5
  gripper_height: 25
  finger_height: 66
smc_rcc_small:
  finger_length: 14
  finger_width: 6.5
  open_width: 48
  tool_changer_height: 31
  flange1_height: 6
  rrc_height: 25
  flange2_height: 5
  gripper_height: 25
  finger_height: 79
thk_soft:
  finger_length: 80
  finger_width: 10
  open_width: 90
  tool_changer_height: 31
  flange_height: 6
  finger_height: 122
  gripper_height: 26


